[platformio]
src_dir = .

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_ldf_mode = deep+
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.4
  knolleary/PubSubClient @ ^2.8
